apiVersion: v1
kind: Service
metadata:
  name: socket-service
  namespace: card-platform
  labels:
    app: socket
spec:
  selector:
    app: socket
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
