#!/bin/bash
# scripts/generate-vapid.sh
# Generates VAPID keys and writes them to the environment secrets file.
# Run once per environment. Idempotent — will not overwrite existing keys.
#
# Usage:
#   ./scripts/generate-vapid.sh [--env staging|production]
#
# Output:
#   .env.{ENV}.secrets — contains VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT
#
# CLAUDE.md rule 14: VAPID keys are generated by this script only.
# Never hardcode VAPID keys in any config file.

set -euo pipefail

# ── Argument parsing ────────────────────────────────────────────────────────────
ENV="staging"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)
      ENV="$2"
      shift 2
      ;;
    --env=*)
      ENV="${1#--env=}"
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Usage: $0 [--env staging|production]" >&2
      exit 1
      ;;
  esac
done

if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
  echo "Error: --env must be 'staging' or 'production', got '$ENV'" >&2
  exit 1
fi

SECRETS_FILE=".env.${ENV}.secrets"

# ── Idempotency check ───────────────────────────────────────────────────────────
if grep -q "VAPID_PUBLIC_KEY=" "$SECRETS_FILE" 2>/dev/null; then
  echo "VAPID keys already present in $SECRETS_FILE — skipping generation"
  exit 0
fi

# ── Generate keys via web-push ─────────────────────────────────────────────────
echo "Generating VAPID keys for $ENV..."

# Verify web-push is available
if ! node -e "require('web-push')" 2>/dev/null; then
  echo "Error: web-push package not found. Install it in apps/worker-service:" >&2
  echo "  cd apps/worker-service && npm install web-push" >&2
  # Try to find it in node_modules
  WEB_PUSH_PATH=$(find . -path "*/node_modules/web-push/src/index.js" -not -path "*/node_modules/*/node_modules/*" 2>/dev/null | head -1)
  if [[ -z "$WEB_PUSH_PATH" ]]; then
    echo "Could not locate web-push in any node_modules directory." >&2
    exit 1
  fi
fi

node -e "
  const webpush = require('web-push');
  const keys = webpush.generateVAPIDKeys();
  process.stdout.write('VAPID_PUBLIC_KEY=' + keys.publicKey + '\n');
  process.stdout.write('VAPID_PRIVATE_KEY=' + keys.privateKey + '\n');
" >> "$SECRETS_FILE"

echo "VAPID_SUBJECT=mailto:admin@platform.example.com" >> "$SECRETS_FILE"

echo "VAPID keys written to $SECRETS_FILE"
echo ""
echo "IMPORTANT: Add $SECRETS_FILE to .gitignore — never commit secrets."
